### ISSUE TITLE
passthrough not supported

### ISSUE THREAD

**Issue by teucode** [LaskasP/TripAdvisor-Python-Scraper-Restaurants-2021#3]
Hi, thankyou for this code 
I got this message while running it at the cmd
"[12304:1944:0726/110659.818:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled"
Can you tell me what actually happen? TIA!

**Comment by teucode** [comment]
I have this problem too
DevTools listening on ws://127.0.0.1:62542/devtools/browser/cda7e239-dc82-4021-89ef-1966d5cdf7cf
[3924:132:0726/113814.407:ERROR:device_event_log_impl.cc(214)] [11:38:14.407] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

**Comment by muhammadanasmahmood** [comment]
Hi, thank you for this code
I got this error
E:\download\TripAdvisor-Python-Scraper-Restaurants-2021-main\TripAdvisor-Python-Scraper-Restaurants-2021-main\scraper.py:56: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('chromedriver.exe')
Traceback (most recent call last):
  File "E:\pythonProject\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "E:\pythonProject\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\pythonProject\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\download\TripAdvisor-Python-Scraper-Restaurants-2021-main\TripAdvisor-Python-Scraper-Restaurants-2021-main\scraper.py", line 56, in <module>     
    driver = webdriver.Chrome('chromedriver.exe')
  File "E:\pythonProject\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "E:\pythonProject\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "E:\pythonProject\lib\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

PS E:\download\TripAdvisor-Python-Scraper-Restaurants-2021-main\TripAdvisor-Python-Scraper-Restaurants-2021-main>
